apiVersion: v1
kind: Service

metadata:
  labels:
    {{- toYaml .Values.podLabels | nindent 4 }}
  name: {{ .Values.service.name | quote }}
  namespace: {{ .Values.namespace.name | quote }}

spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}

  selector:
    {{- toYaml .Values.podLabels | nindent 4 }}

  type: {{ .Values.service.type }}