---
# Source: cloud-netdebug/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: "netdebug"
---
# Source: cloud-netdebug/templates/networkpolicy.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  name: "allow-approved-client"
  namespace: "netdebug"

spec:
  podSelector:
    matchLabels:
      app: netdebug-app

  policyTypes:
    - Ingress

  ingress:
    - from:
        - podSelector:
            matchLabels:
              access: allowed
---
# Source: cloud-netdebug/templates/service.yaml
apiVersion: v1
kind: Service

metadata:
  labels:
    app: netdebug-app
  name: "netdebug-service"
  namespace: "netdebug"

spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80

  selector:
    app: netdebug-app

  type: ClusterIP
---
# Source: cloud-netdebug/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: netdebug-app
  name: netdebug-app
  namespace: netdebug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netdebug-app
  template:
    metadata:
      labels:
        app: netdebug-app
    spec:
      containers:
        - name: netdebug-app
          image: "nginx@sha256:bc5eac5eafc581aeda3008b4b1f07ebba230de2f27d47767129a6a905c84f470"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
